import { Kumbh_Sans, Inter } from 'next/font/google';
import './globals.css';

const kumbhSans = Kumbh_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-kumbh-sans',
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='it'>
      <body
        suppressHydrationWarning
        className={`${kumbhSans.variable} ${inter.variable} antialiased dark:bg-dark-8`}
      >
        {children}
      </body>
    </html>
  );
}
